name: JavaFX CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxtst6 libgl1-mesa-glx libasound2 libgtk-3-0

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: |
          # Start virtual framebuffer
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          # Wait for Xvfb to start
          sleep 3
          
          # Run tests with specific JavaFX and TestFX configurations
          DISPLAY=:99 ./gradlew test \
            -Dprism.order=sw \
            -Dprism.verbose=true \
            -Dglass.platform=gtk \
            -Dheadless.geometry=1024x768-32 \
            -Dtestfx.robot=glass \
            -Dtestfx.headless=true \
            -Dprism.text=t2k \
            --info

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results/test/
            build/reports/tests/test/

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar